### ISSUE TITLE
Proportional invest defaults to wftm

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beets-frontend#105]
tried investing with the proportional investment. It defaults to wftm and therefore I have 0$ to invest. Took me a bit to get that I need to switch to ftm. Not sure how this could be done differently. Maybe use the version of ftm where I have a balance? or show both somehow?

![Image](https://user-images.githubusercontent.com/93920061/183584031-7e10de97-d9bf-4752-800f-6f382d2dc4f9.png)

**Comment by mobiusTripper-crypto** [comment]
I have a solution for the frontend which picks the the token with the larger balance, but perhaps it would be better to default it to FTM? and this would be most easily done by changing the order in which the native tokens are added in the function `getActionOptionsForPoolToken()`?

**Comment by mobiusTripper-crypto** [comment]
Also need to select the largest user balance on join / exit for boosted pools
