### ISSUE TITLE
Improper rounding when staking BPT

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beets-frontend#107]
I have unstaked fidelio BPT in my wallet. Banner tells me to stake. I try to stake but it exceeds my balance because it's rounded

![Image](https://user-images.githubusercontent.com/93920061/183584695-9df66a06-aa16-4b30-af00-6b6a98a98147.png)

And I can't edit the amount which prevents me from staking 100% of the BPTs

**Comment by franzns** [comment]
![Image](https://user-images.githubusercontent.com/93920061/183587748-4111afb6-1103-4e8a-aacd-ac898a65b416.png)

for some reason it works here. Let's me stake and uses the max amount possible instead of what is displayed as max on the dialog

**Comment by danielmkm** [comment]
this was an issue with fbeets, not a rounding issue
