### ISSUE TITLE
Stop confetti animation on swap succeed

### ISSUE THREAD

**Issue by 0xSkly** [beethovenxfi/beets-frontend#110]
The infinite confetti animation is quite distracting when trying to read the receipt after a swap. Think its enough to show the animation once or twice :)

![Image](https://user-images.githubusercontent.com/91403802/183593309-4e3d11bb-19b1-40ef-9ba1-61c49a346500.png)

**Comment by danielmkm** [comment]
no sir, more confetti!

**Comment by danielmkm** [comment]
i moved the confetti behind the modal so its at least not as invasive. will look at having it time out
