### ISSUE TITLE
When not able to invest proportionally, its not obvious how to proceed

### ISSUE THREAD

**Issue by 0xSkly** [beethovenxfi/beets-frontend#111]
Its a bit confusing when you cannot invest proportionally that you have to go on the 'Customize my investment' button. Does not feel intuitive, even i was wondering what i need to do. wanted to edit the numbers next to the coins.  Maybe add an info banner or something that if you want to not invest proportionally you have to 'customize' the investment or just go directly to the non proportional invest screen if you cannot invest proportionally

![Image](https://user-images.githubusercontent.com/91403802/183594526-044fd1f2-da0b-4062-9fdd-31ed4267bfa8.png)

**Comment by danielmkm** [comment]
![Screenshot 2022-08-09 at 10 47 13](https://user-images.githubusercontent.com/91405705/183606378-2af38964-5f62-4c08-8c3c-5afb5a024f91.png)

Changed the customize button to primary when proportional is disabled. Added an alert message.

The headline says "Pool tokens in my wallet," not sure about the wanting to edit the numbers statement :)

**Comment by 0xSkly** [comment]
Haha yea who has time to read text nowadays 🙈
