### ISSUE TITLE
fBeets in wallet trigger 'you have unstaked BPT' on fidelio duetto pool page

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beets-frontend#112]
I have fBeets in the wallet and the fidelio duetto pool page tells me to stake the BPT. Related to #107 I assume.

**Comment by danielmkm** [comment]
![Screenshot 2022-08-09 at 11 11 50](https://user-images.githubusercontent.com/91405705/183611457-8c1ea22b-463e-4dc1-b238-39f12b14107e.png)


if you have fbeets or bpt you're now directed to the stake page.
