### ISSUE TITLE
APR pop over displays everything double

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beets-frontend#117]
![Image](https://user-images.githubusercontent.com/93920061/184077525-4c9d74bb-7396-4e8c-988a-5d0740941bb0.png)

Switching back and forth between the pool overview and pool detail of https://v2.beets.fi/pool/0xc0064b291bd3d4ba0e44ccfc81bf8e7f7a579cd200000000000000000000042c causes the APR pop over in the pool detail to display duplicates, see screenshot. Only for some limited time, fixes itself.

**Comment by groninge01** [comment]
![image](https://user-images.githubusercontent.com/20125808/184085253-87a05cca-7cf6-41f9-b268-45e797e29819.png)

3 times...

**Comment by groninge01** [comment]
@franzns Can you close this one too when [the issue](https://github.com/beethovenxfi/beethovenx-backend/issues/81) is fixed in the backend?

**Comment by 0xSkly** [comment]
should be fixed by acda28ec80210f6f4d18ba9252635dbed89cc00a
