### ISSUE TITLE
graph display on swap - sell token / buy token or toggle?

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beets-frontend#133]
https://discord.com/channels/885764705526882335/1006904489422356573/1009148528184021082

![Image](https://user-images.githubusercontent.com/93920061/185036538-d7e804a0-71a0-4e67-8bf4-87edd98f49e0.png)

Personally, I agree with him. The graph should always display sell token / buy token.

Daniel advocated a toggle, but imo the toggle would be the arrow to switch buy/sell tokens.

**Comment by danielmkm** [comment]
A toggle is more appropriate here, when you're buying FTM with USDC, this is what you would see in that instance:
![Screenshot 2022-08-18 at 11 46 53](https://user-images.githubusercontent.com/91405705/185365553-5a2f6e00-5157-42d3-b7e6-8cad2725869e.png)

**Comment by franzns** [comment]
Yeah agree, toggle makes sense. A trade can always be seen in two ways, either buying ftm with usdc or selling usdc for fantom :)
