### ISSUE TITLE
coin swap rate difference in graph and card

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beets-frontend#134]
In the graph 1wftm = 0.37087 where as in the card below the swap it says 1wftm = 0.374832 . 

![Image](https://user-images.githubusercontent.com/93920061/185036851-bb073a63-5a25-41ee-bb19-0a78b5868f92.png)

**Comment by danielmkm** [comment]
![Screenshot 2022-08-18 at 11 56 48](https://user-images.githubusercontent.com/91405705/185367924-179f221c-73c5-45d1-9dc5-35f3b1c058f7.png)

**Comment by danielmkm** [comment]
added an info button, that is the coingecko rate, the rate on the card is the swap rate. This is why it says `Compared to - within 1.06%` directly below it.
