### ISSUE TITLE
Balances show wrong amounts for nested pools

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beets-frontend#193]
Balances for the reaper vaults seem to be wrong on the pool detail pages:

spartan spirit (https://op.beets.fi/pool/0x479a7d1fcdd71ce0c2ed3184bfbe9d23b92e8337000000000000000000000049):
- shouldn't rf-a-DAI balance also show something like 0.000002? or is that actually the correct one?
- rf-a-usdt shows 0.0000001 worth 125k, rf-a-usdc shows 0.0000002 worth 154k (balance is doubled, value isn't)

![Image](https://user-images.githubusercontent.com/93920061/200013661-082b6aca-c94b-4a4a-aef5-05f0be874f34.png)

steady beets: (https://op.beets.fi/pool/0x6222ae1d2a9f6894da50aa25cb7b303497f9bebd000000000000000000000046)

- shouldn't rf-a-DAI balance also show something like 0.000002? or is that actually the correct one?
- rf-a-usdt and rf-a-usdc balances align here with the value

![Image](https://user-images.githubusercontent.com/93920061/200013433-322aa333-da66-4416-98d8-3a94bc005d51.png)

not sure if it is the same issue or not :)

**Comment by danielmkm** [comment]
Balances are shown correctly, this is a side effect or reaper vault tokens representing 6 decimal values in 18 decimals. Not an issue, although it does look strange, we should change it to show 10e-x when its less, but fine for now.
