### ISSUE TITLE
Handle invest transaction error gracefully

### ISSUE THREAD

**Issue by danielmkm** [beethovenxfi/beets-frontend#24]
Currently a failed invest transaction is shown as successful in the UI. Investigate this.

**Comment by groninge01** [comment]
@danielmkm How do I fail a transaction? Declining it shows up in the UI.

**Comment by danielmkm** [comment]
good question, it was happening sporadically

**Comment by danielmkm** [comment]
This is still an issue, ideally resolve before we launch

**Comment by danielmkm** [comment]
still haven't been able to reproduce this. will continue to look out for it

**Comment by franzns** [comment]
I was able to let the harvest all transaction fail by setting the gas limit to something small (50000). Unfortunately also didn't work every time...
