### ISSUE TITLE
Need to set up a cron strategy that will keep the cached pages up to date on vercel.

### ISSUE THREAD

**Issue by danielmkm** [beethovenxfi/beets-frontend#32]

**Comment by groninge01** [comment]
![image](https://user-images.githubusercontent.com/20125808/180227825-0af1c06c-09ec-424a-80d6-7dc044eed4ff.png)

?

**Comment by danielmkm** [comment]
This is not enough.
https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration

Skly is working on this

**Comment by 0xSkly** [comment]
closed in favour of https://github.com/beethovenxfi/beethovenx-backend/issues/44 since its a backend issue
