### ISSUE TITLE
Beethoven X logo appears blurry when scaled down.

### ISSUE THREAD

**Issue by danielmkm** [beethovenxfi/beets-frontend#37]
After you scroll down, the scale down beethoven x logo looks a bit blurry on some screens.

![Screenshot 2022-07-22 at 13 33 48](https://user-images.githubusercontent.com/91405705/180430960-eacb483e-74e1-4ae8-a942-0a4137e12727.png)

**Comment by groninge01** [comment]
@danielmkm The blurry looks only appear on desktop browsers it appears. When you zoom out to 200% everything looks fine. I tried several options but until now to no effect.

**Comment by danielmkm** [comment]
removed the scaling, was the only way we could find to resolve this
