### ISSUE TITLE
Port balancer pool creator 

### ISSUE THREAD

**Issue by danielmkm** [beethovenxfi/beets-frontend#43]
https://app.balancer.fi/#/pool/create

Balancer's pool creator is clearly a superior experience to our existing one. Would suggest we port their's into our project :)

**Comment by groninge01** [comment]
![image](https://user-images.githubusercontent.com/20125808/180641856-6494b256-5846-4cfb-9f16-bcfafd82a3ff.png)

Suggestion: always give the 'rest' to the last (unlocked) token in the list.

**Comment by danielmkm** [comment]
We have a volunteer!
