### ISSUE TITLE
Overlap in withdrawal of stS

### ISSUE THREAD

**Issue by thebraveman17** [beethovenxfi/beets-frontend#484]
When you navigate to the withdraw menu of the [staking page](https://beets.fi/stake), the stS amount overlaps the withdrawal date because there's a large number of decimals.

<img width="531" alt="Screenshot 2024-12-19 at 21 14 53" src="https://github.com/user-attachments/assets/4021692c-22df-42c6-8da6-eb32fe62f543" />

**Comment by Hushg2** [comment]
Hello @thebraveman17  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by groninge01** [comment]
@thebraveman17 don't click on any links in the comments (just deleted one such comment)

**Comment by groninge01** [comment]
this should be fixed now
