### ISSUE TITLE
Withdraw modal sometimes blank (error token does not exist in pool)

### ISSUE THREAD

**Issue by 0xSkly** [beethovenxfi/beets-frontend#63]
Sometimes when switching between pools and hitting the withdraw button, the modal opens blank with an error in the console that a token with address does not exist in the pool. It does not say the token address (might be undefined? )
![image](https://user-images.githubusercontent.com/91403802/182137367-6e2a67e4-3037-4eea-9698-5e7ff7592ba3.png)

**Comment by danielmkm** [comment]
@mobiusTripper-crypto if you can reproduce this, would be great.

**Comment by danielmkm** [comment]
was an issue with state persistence between pools, this should be resolved
