### ISSUE TITLE
Shows 0 BPT for some pools on home screen

### ISSUE THREAD

**Issue by 0xSkly** [beethovenxfi/beets-frontend#64]
Under my investments on the home screen, it shows 0 BPT for the fidelio duetto pool but it shows a dollar value
![image](https://user-images.githubusercontent.com/91403802/182137870-3da3aaef-438b-4ed6-ada7-d668a6ecc5a5.png)

**Comment by danielmkm** [comment]
fidelio duetto sir :(

**Comment by danielmkm** [comment]
this should be resolved.
