### ISSUE TITLE
All pending rewards show under 1 pool, even though i am in 2 pools

### ISSUE THREAD

**Issue by 0xSkly** [beethovenxfi/beets-frontend#66]
Even though i should get rewards for fidelio duetto and Beet Masons's Oath, pending rewards on the pool detail only show on the fidelio duetto
![image](https://user-images.githubusercontent.com/91403802/182138690-35af952b-43a1-4ba2-92db-1bdd69a131a1.png)
![image](https://user-images.githubusercontent.com/91403802/182138728-308eb19e-3800-4b9d-abcb-e375ee796404.png)

**Comment by danielmkm** [comment]
oath pool doesn't have any active rewards sir

**Comment by 0xSkly** [comment]
Well then this popup is a little misleading, isnt it, sir :) 
![image](https://user-images.githubusercontent.com/91403802/182185633-5da73889-fef6-4c4d-ac70-946afe7470bd.png)

**Comment by danielmkm** [comment]
sir, looks like when the farm allocPoint toggle to 0, it's not deleting the last apr record from the database.

**Comment by danielmkm** [comment]
The issue of incorrect beets reward apr should be resolved here
https://github.com/beethovenxfi/beethovenx-backend/commit/b189d24734c9a82bc811e8be17b8cb83f20432fc
