### ISSUE TITLE
Mor Steady Beets Boosted error on Invest

### ISSUE THREAD

**Issue by mobiusTripper-crypto** [beethovenxfi/beets-frontend#70]
For the Mor Steady Beets Boosted pool. When choose custom invest option. DAI and USDC are linked. So decimal overflow on the USDC input when entering more than 6 decimals of DAI.

Open Mor Steady pool view
Choose Invest
Choose Custom 
Use slider for DAI, or enter more than 6 decimals.

![image](https://user-images.githubusercontent.com/99622829/182260562-bc5590f8-fafc-450d-8fbe-0a89ec66796a.png)

**Comment by danielmkm** [comment]
Boosted pool and stable pool invest is not yet implemented.

**Comment by danielmkm** [comment]
This is resolved
