### ISSUE TITLE
Swap - only send sor query after an input delay

### ISSUE THREAD

**Issue by 0xSkly** [beethovenxfi/beets-frontend#79]
Currently the sor (backend) is queried on each key press, i'd suggest add a little backoff timer so it only sends once the user stops typing to reduce load
![image](https://user-images.githubusercontent.com/91403802/182597045-8c3837b2-4d84-48d4-81fc-496fd73991c2.png)

**Comment by danielmkm** [comment]
![Screenshot 2022-08-03 at 20 15 25](https://user-images.githubusercontent.com/91405705/182679877-828cb96b-7645-43df-8862-4c791007a434.png)

It's already on a 300ms debounce sir, just starts the spinner as soon as you start typing.
