### ISSUE TITLE
Swap - not enough liquidity (?) not handled gracefully

### ISSUE THREAD

**Issue by 0xSkly** [beethovenxfi/beets-frontend#84]
When there is presumably (?) not enough liquidity to make a trade, it just shows `0` with a `NaN` as price impact
![image](https://user-images.githubusercontent.com/91403802/182778230-7e990062-3c38-4eff-b552-9449bf472b88.png)

**Comment by 0xSkly** [comment]
aha ok, yea hard to say

**Comment by danielmkm** [comment]
closing for now, can revisit this
