### ISSUE TITLE
Pending rewards flickers on optimism

### ISSUE THREAD

**Issue by danielmkm** [beethovenxfi/beets-frontend#89]

**Comment by danielmkm** [comment]
For networks with the gauge reward helper, it tries to preserve reward amounts on polling refetches to avoid the flickering. needs to be tested.

**Comment by franzns** [comment]
apparently the new RPC did not resolve this issue.

**Comment by franzns** [comment]
also please test and try this RPC node: https://rpc.ankr.com/optimism
