### ISSUE TITLE
Withdraw button on pool details page looks disabled

### ISSUE THREAD

**Issue by 0xSkly** [beethovenxfi/beets-frontend#90]
Button looks like its grayed out / disabled. might be confusing
![image](https://user-images.githubusercontent.com/91403802/182847927-253bf333-1df5-44d2-a5f9-14bd5cfd38b6.png)

**Comment by danielmkm** [comment]
Kinda agree, but that's the secondary style we've got at the moment. Disabled looks pretty different though.

![Screenshot 2022-08-04 at 15 29 15](https://user-images.githubusercontent.com/91405705/182859052-48ae4bbd-e539-4d22-963d-ccf5da6c9c57.png)
