### ISSUE TITLE
Graph filter dropdown in pool page truncated line-height for select options (Safari) 

### ISSUE THREAD

**Issue by veeBeetX** [beethovenxfi/beets-frontend#96]
Chrome/FF no issue.
Tnx, vee.
<img width="642" alt="image" src="https://user-images.githubusercontent.com/105176374/182944160-a83e2eeb-2789-4553-8311-31b2d72525c6.png">

**Comment by danielmkm** [comment]
Can you get this one @groninge01

**Comment by groninge01** [comment]
Not an issue anymore.
